# Generated by Django 5.2 on 2025-05-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VehicleConnectApp', '0002_vehicle_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='qr_token',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
